repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace # removes extra spaces
      - id: end-of-file-fixer # ensures file ends with newline
      - id: check-yaml # checks YAML files for syntax

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black # formats Python code automatically
